apiVersion: apps/v1
kind: Deployment
metadata:
  name: classifier-deployment
spec:
  selector:
    matchLabels:
      app: classifier
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: classifier
    spec:
      containers:
      - name: broker
        image: malachyiii/broker
        ports:
        - containerPort: 1883
      - name: listener
        image: malachyiii/listener
      - name: classifier
        image: malachyiii/classifier
