apiVersion: apps/v1
kind: Deployment
metadata:
  name: classifier-deployment
spec:
  selector:
    matchLabels:
      app: classifier
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: classifier
    spec:
      containers:
      - name: classifier
        image: malachyiii/classifier
        volumeMounts:
        - mountPath: /dev/video0
          name: dev-video0
        securityContext:
          privileged: true
      volumes:
      - name: dev-video0
        hostPath:
          path: /dev/video0
